### ISSUE TITLE
Keras and Tensorflow verions

### ISSUE THREAD

**Issue by tAndreaniSanofi** [dongminjung/VAExprs#1]
Hello, which versions of Keras and Tensorflow are used? Thank you in advance for any reply. Currently i have this issue which might be related to my Keras version (2.14): 

Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  **AttributeError: 'TensorBoard' object has no attribute '_should_trace'**
Run `reticulate::py_last_error()` for details.

when i do reticulate::py_last_error(), this is the output:

Traceback (most recent call last):
  File "/opt/py/conda/PyLib_Common/envs/ganGenerativeData/lib/python3.9/site-packages/keras/src/engine/training_v1.py", line 1059, in predict
    return func.predict(
  File "/opt/py/conda/PyLib_Common/envs/ganGenerativeData/lib/python3.9/site-packages/keras/src/engine/training_arrays_v1.py", line 801, in predict
    return predict_loop(
  File "/opt/py/conda/PyLib_Common/envs/ganGenerativeData/lib/python3.9/site-packages/keras/src/engine/training_arrays_v1.py", line 229, in model_iteration
    callbacks = cbks.configure_callbacks(
  File "/opt/py/conda/PyLib_Common/envs/ganGenerativeData/lib/python3.9/site-packages/keras/src/callbacks.py", line 100, in configure_callbacks
    callback_list = CallbackList(callbacks)
  File "/opt/py/conda/PyLib_Common/envs/ganGenerativeData/lib/python3.9/site-packages/keras/src/callbacks.py", line 239, in __init__
    self._batch_hooks_support_tf_logs = all(
  File "/opt/py/conda/PyLib_Common/envs/ganGenerativeData/lib/python3.9/site-packages/keras/src/callbacks.py", line 242, in <genexpr>
    if cb._implements_train_batch_hooks()
  File "/opt/py/conda/PyLib_Common/envs/ganGenerativeData/lib/python3.9/site-packages/keras/src/callbacks.py", line 2793, in _implements_train_batch_hooks
    return self._should_trace or self.write_steps_per_second
**AttributeError: 'TensorBoard' object has no attribute '_should_trace'**

a quick google search is telling me to update to the 2.3 version: https://github.com/dickreuter/neuron_poker/issues/63

**Comment by dongminjung** [comment]
Hello. You can find versions of dependencies of Bioconductor servers.
https://bioconductor.org/checkResults/release/bioc-LATEST/nebbiolo2-R-instpkgs.html
https://bioconductor.org/checkResults/release/bioc-LATEST/palomino4-R-instpkgs.html
https://bioconductor.org/checkResults/release/bioc-LATEST/merida1-R-instpkgs.html

**Comment by tAndreaniSanofi** [comment]
Thank you, I am going to install all the packages required for the package as described here:

https://www.bioconductor.org/packages/devel/bioc/manuals/VAExprs/man/VAExprs.pdf 

These are: keras, mclust, Imports SingleCellExperiment, SummarizedExperiment, tensorflow, scater, CatEncoders, DeepPINCS, purrr, DiagrammeR, stats, SC3, knitr, testthat, reticulate, rmarkdown.

I will keep you posted in case..
